"""Check that the local task1 pi05 checkpoints are byte-identical to their Hub repos.

Intent: answer "is the online model the same as the local one" with evidence rather than a
clean upload log, which LP §Q18 records as insufficient. The Hub already publishes a content
hash for every file -- `lfs.sha256` for LFS entries and a git blob sha1 for the plain text ones
-- so this hashes the local file and compares, downloading nothing, loading no policy, and
touching no GPU. A matching hash proves bit-identity, which is strictly stronger than a
per-tensor `torch.equal` sweep. Expected lifetime: rerun after any checkpoint push.

    python3 claude_test/verify_pi05_task1_hub_parity.py [--episodes 50 100 200] [--policy pi05]
"""

import argparse
import hashlib
import sys
from pathlib import Path

from huggingface_hub import HfApi

REPO_ROOT = Path(__file__).resolve().parent.parent
TASK_NAME = "FR5_task1_move_the_brown_colored_glass_bottle_to_the_designated_location"
EPISODE_COUNTS = (50, 100, 200)
WEIGHTS_FILE = "model.safetensors"

# push_to_hub generates these; they never exist in the local checkpoint directory.
EXPECTED_HUB_ONLY = frozenset({".gitattributes", "README.md"})

HASH_CHUNK_BYTES = 8 * 1024 * 1024


def local_checkpoint_dir(root, task, episodes, policy):
    return root / "outputs/train" / f"{task}_{episodes}_{policy}_b200" / "checkpoints/last/pretrained_model"


def hub_repo_id(owner, task, episodes, policy):
    return f"{owner}/{task}_{episodes}_{policy}_b200_model"


def read_hub_tree(api, repo_id):
    """Map every file in the Hub repo to (size, lfs_sha256 or None, git_blob_sha1)."""
    tree = {}
    for entry in api.list_repo_tree(repo_id, recursive=True, expand=True):
        lfs = getattr(entry, "lfs", None)
        tree[entry.path] = (
            getattr(entry, "size", None),
            getattr(lfs, "sha256", None) if lfs else None,
            getattr(entry, "blob_id", None),
        )
    return tree


def hash_file_sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        while chunk := handle.read(HASH_CHUNK_BYTES):
            digest.update(chunk)
    return digest.hexdigest()


def hash_file_git_blob(path, size):
    """Reproduce `git hash-object`: sha1 over a "blob <size>\\0" header plus the content."""
    digest = hashlib.sha1(b"blob %d\0" % size)  # noqa: S324 -- git's format, not a security hash.
    with open(path, "rb") as handle:
        while chunk := handle.read(HASH_CHUNK_BYTES):
            digest.update(chunk)
    return digest.hexdigest()


def compare_one_file(local_path, hub_size, hub_lfs_sha256, hub_blob_sha1):
    """Return (status, detail) for a single file that exists both locally and on the Hub."""
    local_size = local_path.stat().st_size
    if local_size != hub_size:
        return "SIZE", f"local {local_size} != hub {hub_size}"

    if hub_lfs_sha256 is not None:
        local_hash = hash_file_sha256(local_path)
        expected, kind = hub_lfs_sha256, "sha256"
    else:
        local_hash = hash_file_git_blob(local_path, local_size)
        expected, kind = hub_blob_sha1, "git-blob"

    if expected is None:
        return "NOHASH", f"hub published no {kind} hash"
    if local_hash != expected:
        return "HASH", f"{kind} local {local_hash} != hub {expected}"
    return "OK", f"{kind} {local_hash[:16]}..."


def compare_checkpoint(local_dir, tree):
    """Compare one local checkpoint directory against one Hub file tree.

    Returns (rows, is_identical, weights_hash). Files the Hub generates on push are reported
    but do not count as a mismatch.
    """
    rows = []
    identical = True
    weights_hash = None

    if not local_dir.is_dir():
        return [("LOCAL-MISSING", str(local_dir), "directory does not exist")], False, None

    local_files = {path.name for path in local_dir.iterdir() if path.is_file()}

    for name in sorted(local_files | set(tree)):
        if name not in tree:
            rows.append(("LOCAL-ONLY", name, "not published to the Hub"))
            identical = False
            continue
        hub_size, hub_lfs_sha256, hub_blob_sha1 = tree[name]
        if name not in local_files:
            if name in EXPECTED_HUB_ONLY:
                rows.append(("HUB-ONLY", name, "generated by push_to_hub, expected"))
            else:
                rows.append(("HUB-ONLY", name, "missing locally"))
                identical = False
            continue

        status, detail = compare_one_file(local_dir / name, hub_size, hub_lfs_sha256, hub_blob_sha1)
        rows.append((status, name, detail))
        if status != "OK":
            identical = False
        elif name == WEIGHTS_FILE:
            weights_hash = hub_lfs_sha256

    return rows, identical, weights_hash


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--task", default=TASK_NAME, help="job-name stem shared by the local dir and the repo"
    )
    parser.add_argument("--episodes", type=int, nargs="+", default=list(EPISODE_COUNTS))
    parser.add_argument("--policy", default="pi05", help="policy tag in the directory and repo name")
    parser.add_argument("--owner", default="coport-uni")
    parser.add_argument("--local-root", type=Path, default=REPO_ROOT)
    args = parser.parse_args()

    api = HfApi()
    print(f"Hub identity: {api.whoami().get('name')}\n")

    verdicts = {}
    weights_hashes = {}

    for episodes in args.episodes:
        local_dir = local_checkpoint_dir(args.local_root, args.task, episodes, args.policy)
        repo_id = hub_repo_id(args.owner, args.task, episodes, args.policy)
        print(f"=== {episodes} episodes")
        print(f"    local {local_dir}")
        print(f"    hub   {repo_id}")

        try:
            tree = read_hub_tree(api, repo_id)
        except Exception as error:  # noqa: BLE001 -- any Hub failure is a reportable verdict.
            print(f"    HUB ERROR: {type(error).__name__}: {error}\n")
            verdicts[episodes] = False
            continue

        rows, identical, weights_hash = compare_checkpoint(local_dir, tree)
        for status, name, detail in rows:
            print(f"    {status:13s} {name:62s} {detail}")
        print(f"    -> {'IDENTICAL' if identical else 'MISMATCH'}\n")

        verdicts[episodes] = identical
        if weights_hash is not None:
            weights_hashes[episodes] = weights_hash

    print("=== summary")
    for episodes, identical in verdicts.items():
        print(f"    {episodes:>4} episodes: {'IDENTICAL' if identical else 'MISMATCH'}")

    # A pass could otherwise be produced by the same file having been pushed to all three repos.
    distinct = len(set(weights_hashes.values()))
    print(f"    distinct {WEIGHTS_FILE} hashes: {distinct} of {len(weights_hashes)} verified models")
    if weights_hashes and distinct != len(weights_hashes):
        print("    WARNING: two models share weights -- check which checkpoint was pushed where")
        return 1

    return 0 if all(verdicts.values()) else 1


if __name__ == "__main__":
    sys.exit(main())
